=== niemilosz/Hipertext-Hipermedia-2025/mojehobby.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:simpleType name="typ_Trudnosci">
        <xs:restriction base="xs:string">
            <xs:enumeration value="łatwa"/>
            <xs:enumeration value="średnia"/>
            <xs:enumeration value="wysoka"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="typ_TakNie">
        <xs:restriction base="xs:string">
            <xs:enumeration value="tak"/>
            <xs:enumeration value="nie"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="typ_Statusu">
        <xs:restriction base="xs:string">
            <xs:enumeration value="zdobyty"/>
            <xs:enumeration value="planowany"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="typ_Roku">
        <xs:restriction base="xs:gYear">
            <xs:minInclusive value="2024"/>
            <xs:maxInclusive value="2100"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="typ_URL">
        <xs:restriction base="xs:anyURI">
            <xs:pattern value="https?://.+"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="typ_Tekstu">
        <xs:restriction base="xs:string">
            <xs:maxLength value="200"/>
        </xs:restriction>
    </xs:simpleType>





    <xs:complexType name="typ_Kraje">
        <xs:sequence>
            <xs:element name="kraj" type="xs:string" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="graniczny" type="typ_TakNie" use="required"/>
    </xs:complexType>

    <xs:complexType name="typ_Autor">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="student" type="typ_TakNie" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="typ_Nazwa">
        <xs:simpleContent>
            <xs:extension base="typ_Tekstu"/>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="typ_Wysokosc">
        <xs:simpleContent>
            <xs:extension base="xs:positiveInteger"/>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="typ_Opis">
        <xs:simpleContent>
            <xs:extension base="typ_Tekstu"/>
        </xs:simpleContent>
    </xs:complexType>





    <xs:group name="grupa_Szczytow">
        <xs:sequence>
            <xs:element name="nazwa" type="typ_Nazwa"/>
            <xs:element name="wysokość" type="typ_Wysokosc"/>
            <xs:element name="opis" type="typ_Opis"/>
            <xs:element name="link" type="typ_URL"/>
            <xs:element name="zdjecie" type="typ_URL"/>
        </xs:sequence>
    </xs:group>

    <xs:attributeGroup name="atrybuty_Szczytow">
        <xs:attribute name="trudność" type="typ_Trudnosci" use="required"/>
        <xs:attribute name="najwyższy" type="typ_TakNie" use="required"/>
        <xs:attribute name="status" type="typ_Statusu" use="required"/>
    </xs:attributeGroup>





    <xs:complexType name="typ_ListaSzczytow">
        <xs:sequence>
            <xs:element name="szczyt" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:group ref="grupa_Szczytow"/>
                    <xs:attributeGroup ref="atrybuty_Szczytow"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="typ_ListaPlanowanych">
        <xs:sequence>
            <xs:element name="szczyt_planowany" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="nazwa" type="typ_Nazwa"/>
                        <xs:element name="wysokość" type="typ_Wysokosc"/>
                        <xs:element name="kraje" type="typ_Kraje"/>
                        <xs:element name="zdjecie" type="typ_URL"/>
                    </xs:sequence>
                    <xs:attribute name="korona_ziemi" type="typ_TakNie" use="required"/>
                    <xs:attribute name="status" type="typ_Statusu" use="required"/>
                    <xs:attribute name="rok" type="typ_Roku" use="required"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>





    <xs:element name="hobby">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="informacje">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="zainteresowanie" type="typ_Tekstu"/>
                            <xs:element name="opis_glowny" type="typ_Tekstu"/>
                            <xs:element name="autor" type="typ_Autor"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="zdobyte">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="pasmo_górskie">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="tatry" type="typ_ListaSzczytow"/>
                                        <xs:element name="karkonosze" type="typ_ListaSzczytow"/>
                                        <xs:element name="karpaty" type="typ_ListaSzczytow"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="planowane">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="kontynent">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="afryka" type="typ_ListaPlanowanych"/>
                                        <xs:element name="europa" type="typ_ListaPlanowanych"/>
                                        <xs:element name="azja" type="typ_ListaPlanowanych"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== niemilosz/Hipertext-Hipermedia-2025/mojehobby.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="mojehobby.xsl"?>
<hobby xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="mojehobby.xsd">

    <informacje>
        <zainteresowanie>
            Turystyka gorska
        </zainteresowanie>
        <opis_glowny>
            Strona ukazuje moje hobby, czyli turystyke gorska, przedstawiam jedne z piekniejszych z polskich szczytow oraz moje plany co do zdobywania kolejnych, tym razem poza Polska.
        </opis_glowny>
        <autor student="tak">
            Milosz Niezurawski, s202375
        </autor>
    </informacje>

    <zdobyte>
        <pasmo_górskie>
            <tatry>
                <szczyt trudność="wysoka" najwyższy="tak" status="zdobyty">
                    <nazwa>Rysy</nazwa>
                    <wysokość>2499</wysokość>
                    <opis>Najwyzszy szczyt Tatr i Polski.</opis>
                    <link>https://pl.wikipedia.org/wiki/Rysy</link>
                    <zdjecie>https://upload.wikimedia.org/wikipedia/commons/8/87/Rysy%2C_szczyt.jpg</zdjecie>
                </szczyt>
                <szczyt trudność="średnia" najwyższy="nie" status="zdobyty">
                    <nazwa>Kasprowy Wierch</nazwa>
                    <wysokość>1987</wysokość>
                    <opis>Jeden z popularniejszych szczytow z kolejka linowa.</opis>
                    <link>https://www.pkl.pl/kasprowy-wierch/kasprowy.html</link>
                    <zdjecie>https://i-tatry.pl/wp-content/uploads/2014/11/szlak-kasprowy-wierch-przelecz-liliowe-7.jpg</zdjecie>
                </szczyt>
                <szczyt trudność="średnia" najwyższy="nie" status="zdobyty">
                    <nazwa>Giewont</nazwa>
                    <wysokość>1894</wysokość>
                    <opis>Symbol Zakopanego ktory na swoim szczycie posiada metalowy krzyz.</opis>
                    <link>https://pl.wikipedia.org/wiki/Giewont</link>
                    <zdjecie>https://i-tatry.pl/wp-content/uploads/2014/10/giewont-1.jpg</zdjecie>
                </szczyt>
            </tatry>
            <karkonosze>
                <szczyt trudność="średnia" najwyższy="tak" status="zdobyty">
                    <nazwa>Sniezka</nazwa>
                    <wysokość>1603</wysokość>
                    <opis>Najwyzszy szczyt Karkonoszy.</opis>
                    <link>https://pl.wikipedia.org/wiki/%C5%9Anie%C5%BCka</link>
                    <zdjecie>https://slowroad.pl/wp-content/uploads/sites/23/2023/09/G230182.jpg</zdjecie>
                </szczyt>
                <szczyt trudność="średnia" najwyższy="nie" status="zdobyty">
                    <nazwa>Snieznik</nazwa>
                    <wysokość>1425</wysokość>
                    <opis>Szczyt znajdujacy sie na granicy polsko-czeskiej.</opis>
                    <link>https://pl.wikipedia.org/wiki/%C5%9Anie%C5%BCnik_(g%C3%B3ra)</link>
                    <zdjecie>https://plannawypad.pl/wp-content/uploads/2024/01/snieznik-dron-9.jpg</zdjecie>
                </szczyt>
                <szczyt trudność="łatwa" najwyższy="nie" status="zdobyty">
                    <nazwa>Wielka Sowa</nazwa>
                    <wysokość>1015</wysokość>
                    <opis>Najwyzszy szczyt Gor Sowich.</opis>
                    <link>https://pl.wikipedia.org/wiki/Wielka_Sowa</link>
                    <zdjecie>https://trasynawczasy.pl/1054-lightbox_default/wielka-sowa-petla-z-przeleczy-walimskiej.jpg</zdjecie>
                </szczyt>
            </karkonosze>
            <karpaty>
                <szczyt trudność="wysoka" najwyższy="tak" status="zdobyty">
                    <nazwa>Babia Gora</nazwa>
                    <wysokość>1725</wysokość>
                    <opis>Krolowa Beskidow - najwyzszy szczyt Beskidow</opis>
                    <link>https://pl.wikipedia.org/wiki/Babia_G%C3%B3ra</link>
                    <zdjecie>https://gadulec.pl/wp-content/uploads/2020/05/DSC02880.jpg</zdjecie>
                </szczyt>
                <szczyt trudność="średnia" najwyższy="nie" status="zdobyty">
                    <nazwa>Pilsko</nazwa>
                    <wysokość>1557</wysokość>
                    <opis>Drugi najwyzszy szczyt Beskidow</opis>
                    <link>https://pl.wikipedia.org/wiki/Pilsko</link>
                    <zdjecie>https://hasajacezajace.com/wp-content/uploads/2021/09/Pilsko-43.jpg</zdjecie>
                </szczyt>
                <szczyt trudność="średnia" najwyższy="nie" status="zdobyty">
                    <nazwa>Klimczok</nazwa>
                    <wysokość>1117</wysokość>
                    <opis>Popularny szczyt w Beskidzie Slaskim - Polecam</opis>
                    <link>https://pl.wikipedia.org/wiki/Klimczok</link>
                    <zdjecie>https://szlakowe.pl/wp-content/uploads/2021/10/Szczyt-Klimczok-jesienn%C4%85-por%C4%85-widok-na-Beskid-%C5%BBywiecki-Babi%C4%85-G%C3%B3r%C4%99-oraz-Tatry.jpg</zdjecie>
                </szczyt>
            </karpaty>
        </pasmo_górskie>
    </zdobyte>

    <planowane>
        <kontynent>
            <afryka>
                <szczyt_planowany korona_ziemi="tak" status="planowany" rok="2026">
                    <nazwa>Kilimandzaro</nazwa>
                    <wysokość>5885</wysokość>
                    <kraje graniczny="nie">
                        <kraj>Tanzania</kraj>
                    </kraje>
                    <zdjecie>https://drytooling.pl/images/igallery/resized/kilimandzaro-91/kilimandzaro-6-5000-4000-100-c.jpg</zdjecie>
                </szczyt_planowany>
            </afryka>
            <europa>
                <szczyt_planowany korona_ziemi="tak" status="planowany" rok="2028">
                    <nazwa>Mont Blanc</nazwa>
                    <wysokość>4806</wysokość>
                    <kraje graniczny="tak">
                        <kraj>Francja</kraj>
                        <kraj>Wlochy</kraj>
                    </kraje>
                    <zdjecie>https://upload.wikimedia.org/wikipedia/commons/d/d7/Mont_Blanc_from_Punta_Helbronner%2C_2010_July.JPG</zdjecie>
                </szczyt_planowany>
            </europa>
            <azja>
                <szczyt_planowany korona_ziemi="tak" status="planowany" rok="2035">
                    <nazwa>Mount Everest</nazwa>
                    <wysokość>8848</wysokość>
                    <kraje graniczny="tak">
                        <kraj>Nepal</kraj>
                        <kraj>Chiny</kraj>
                    </kraje>
                    <zdjecie>https://bi.im-g.pl/im/68/75/1e/z31937384Q,Chca-zdobyc-Mount-Everest-w-7-dni---Jestesmy-zajet.jpg</zdjecie>
                </szczyt_planowany>
            </azja>
        </kontynent>
    </planowane>

</hobby>
